import { Dimensions, StyleSheet } from 'react-native';
import dimension from '../../values/dimension';
import colors from '../../values/colors';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  flexRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 5,
  },
  viewQrCodeContainer: {
    width: windowWidth - 40,
    marginHorizontal: 10,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewImageProfile: {
    width: windowWidth - 40,
    alignItems: 'center',
    alignSelf: 'center',
    borderWidth: 1,
    backgroundColor: colors.white,
    borderColor: colors.white,
    borderRadius: 20,
    borderBottomColor: colors.purple_blue,
    borderBottomWidth: 7,
    marginVertical: 20,
    marginHorizontal: 10,
    justifyContent: 'center',
    alignContent: 'center',
    padding: 10,
  },
  viewPersonInfo: {
    width: windowWidth - 40,
    alignItems: 'center',
    alignSelf: 'center',
    borderWidth: 1,
    backgroundColor: colors.white,
    borderColor: colors.white,
    borderRadius: 20,
    borderBottomColor: colors.purple_blue,
    borderBottomWidth: 7,
    marginVertical: 20,
    justifyContent: 'center',
    alignContent: 'center',
    padding: 10,
  },
  coverImage: {
    width: windowWidth - 10,
    height: 150,
  },
  viewAvatar: {
    borderWidth: 5,
    borderRadius: 60,
    borderColor: 'white',
    backgroundColor: 'white',
  },
  imgAvatar: {
    width: 130,
    height: 130,
    borderRadius: 60,
    borderBottomColorWidth: 30,
    alignItems: 'center',
    resizeMode: 'contain',
    marginBottom: 15,
  },
  frameAvatar: {
    width: 150,
    height: 150,
    resizeMode: 'contain',
  },
  imgAvatarRight: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
    alignSelf: 'center',
    borderRadius: 60,
    borderBottomColorWidth: 30,
    marginTop: -50,
  },
  marginBottom: {
    marginBottom: 20,
  },
  contentCard: {
    textAlign: 'center',
    paddingHorizontal: 10,
    fontSize: 14,
  },
  imageLogo: { width: 40, height: 40, position: 'absolute', top: 5, left: 5 },
  subTxt: {
    color: colors.black,
    fontSize: 12,
    marginLeft: 10,
  },
  title: {
    color: colors.black,
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '600',
  },
  icShare: { width: 30, height: 30, position: 'absolute', top: 5, right: 5 },
  centeredView: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    backgroundColor: `rgba(0,0,0,0.5)`,
  },
  itemContact: { flexDirection: 'row', alignItems: 'center', padding: 10 },
  avatarContact: { width: 55, height: 55, marginRight: 15, borderRadius: 10 },
  contactTitle: {
    color: colors.black1,
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 5,
  },
  buttonTouchable: {
    zIndex: 10,
  },
  buttonText: {
    fontSize: 21,
    color: 'red',
  },
  maxScreen: {
    width: windowWidth,
    height: windowHeight - 200,
  },
  cardView: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    marginBottom: 10,
  },
  inputView: {
    maxHeight: 70,
    width: '100%',
    backgroundColor: colors.white,
    marginTop: 15,
  },
  txtSave: { color: colors.white, fontWeight: '600', fontSize: 18 },
  txtCancel: { color: colors.purple_blue, fontWeight: '600', fontSize: 18 },
  btnCancel: {
    backgroundColor: colors.white,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.purple_blue,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    flex: 1,

    shadowColor: colors.white,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 2,
  },
  btnSave: {
    backgroundColor: colors.purple_blue,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    flex: 1,
    marginLeft: 10,
  },
  viewActionButton: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    marginTop: 20,
  },
  txtName: {
    color: colors.purple_blue,
    fontSize: 20,
    fontWeight: '500',
    textAlign: 'center',
  },
  viewEditAvatar: {
    backgroundColor: colors.red,

    alignItems: 'center',
  },
  btnAddMoreSocial: {
    padding: 10,
    borderRadius: 60,
    borderWidth: 1,
  },
  btnNavigateSocial: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  selectedItemsButton: {
    backgroundColor: colors.white,
    borderRadius: 5,
  },
  dropdown1BtnTxtStyle: {},
  btnSendRequest: {
    backgroundColor: colors.blue5c,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    padding: 10,
    width: '90%',
    position: 'absolute',
    bottom: 20,
  },
});

export default styles;
